name: Docker Publish (Dev Images)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/**
      - .github/workflows/action_publish-images-**
      - .github/workflows/service_docker-**
      - scripts/**
  schedule:
    - cron: '25 8 * * 1'
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/action_publish-images-**
      - .github/workflows/service_docker-**
      - scripts/**

jobs:
  build-dev-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      # Set to our development repository
      registry-repositories: "docker.io/serversideup/php-dev"
      # Set to the pull request number for PRs, or no prefix for main branch
      tag-prefix: ${{ github.event_name == 'pull_request' && format('{0}-', github.event.pull_request.number) || '' }}
      # Set release type to "latest" for our development if on main, otherwise default to testing
      release-type: ${{ github.ref == 'refs/heads/main' && 'latest' || 'testing' }}
    secrets: inherit