name: Docker Publish (Beta Images)

on:
  workflow_dispatch:
  release:
    types: [prereleased]
  schedule:
    - cron: '25 8 * * 1'

jobs:
  build-beta-images:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      registry-repositories: "docker.io/serversideup/php,ghcr.io/serversideup/php"
      tag-prefix: "beta-"
    secrets: inherit