name: Docker Publish (Production Images)

on:
  # When changes are pushed to the "main" branch, run it
  push:
    branches:
      - main

  # Run every week at 0800 UTC to update the images
  schedule:
    - cron: '0 8 * * 2'

jobs:
  push:
    runs-on: ubuntu-20.04

    # Configure our deployment strategy. Order is important here and we want it to go: CLI < FPM < FPM-NGINX
    strategy:
      # We want to limit the number of jobs to the number of versions that we're offering (since we want the dependency order to be built correctly)
      max-parallel: 3
      # Set our base image and versions here
      matrix:
        ####################################################################################################################
        # Possibly delete this "base-image" thing. (See https://github.com/serversideup/docker-php/issues/8)
        ####################################################################################################################
        # base-image:
        #   - ubuntu:20.04
        php-variation:
          - cli
          - fpm
          - fpm-nginx
          - fpm-apache
        php-version: 
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: generated-dockerfiles/${{ matrix.php-version }}/${{ matrix.php-variation }}/.
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: serversideup/php:beta-${{ matrix.php-version }}-${{ matrix.php-variation }}
  
  update_container_readme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/php
          provider: dockerhub
          short_description: 'PHP images optimized for Laravel, WordPress, and more!'
          readme_file: 'README.md'

  trigger_downstream_jobs:
    needs: push
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger downstream builds
        run: curl --fail --output "/dev/null" --silent --show-error -X POST -F token=${{ secrets.DOWNSTREAM_BUILD_TOKEN }} -F ref=$GITHUB_REF ${{ secrets.DOWNSTREAM_BUILD_WEBHOOK_ENDPOINT }}
