name: Docker Publish (Production Images)

on:
  # When changes are pushed to the "main" branch, run it
  push:
    branches:
      - main

  # Run every week at 0800 UTC to update the images
  schedule:
    - cron: '0 8 * * 2'

jobs:
  build:
    uses: ./.github/workflows/workflow-docker-publish.yml
    with:
      upstream-channel-prefix: ''
      tag-prefix: ''
    secrets: inherit

  
  update_container_readme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/php
          provider: dockerhub
          short_description: 'PHP images optimized for Laravel, WordPress, and more!'
          readme_file: 'README.md'

  trigger_downstream_jobs:
    needs: push
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger downstream builds
        run: curl --fail --output "/dev/null" --silent --show-error -X POST -F token=${{ secrets.DOWNSTREAM_BUILD_TOKEN }} -F ref=$GITHUB_REF ${{ secrets.DOWNSTREAM_BUILD_WEBHOOK_ENDPOINT }}
