name: Docker Publish (Production Images)

on:
  #release
  schedule:
    - cron: '0 8 * * 2'

jobs:
  cli:
    uses: ./.github/workflows/services/docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ''
      tag-prefix: ''
      php-variation: cli
    secrets: inherit

  fpm:
    needs: cli
    uses: ./.github/workflows/services/docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ''
      tag-prefix: ''
      php-variation: fpm
    secrets: inherit

  fpm-nginx:
    needs: fpm
    uses: ./.github/workflows/services/docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ''
      tag-prefix: ''
      php-variation: fpm-nginx
    secrets: inherit

  fpm-apache:
    needs: fpm
    uses: ./.github/workflows/services/docker-build-and-publish.yml
    with:
      upstream-channel-prefix: ''
      tag-prefix: ''
      php-variation: fpm-apache
    secrets: inherit

  update_container_readme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: push README to Dockerhub
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
          repository: serversideup/php
          short-description: ${{ github.event.repository.description }}